name: Publish Release 

on:
  push:
    branches:
      - main

jobs:

  publish-release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: npx yarn
      - run: git config --global user.name 'codetker'
      - run: git config --global user.email 'codetker@sina.com'
      - run: npx lerna version patch --yes
      - run: npx lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PRODUCTION }}